// Portfolio/src/pages/components/home/projects/Projects.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import Saos from 'saos'
    import Projectcard from "../projectcard/Projectcard.svelte";
  
    type Project = {
        id: number;
        name: string;
        html_url: string;
        homepage: string | null;
        image: string;
        repo_url: string;
        project_url: string;
    };
  
    let Title: string = "<Projects/>";
    let projects: Project[] = [];
    let hiddenProjects: string[] = ["Naval-Battle", "LinuxMistery00", "ProgramadorOrientadoaObjetoMain", "Indalo", "Windows95", "Portfolio", "To-Do-List", "E-Commerce", "Tic-Tac-Toe", "Curso-de-Java-RocketSeat", "TextsForYou"];
  
    const openRepository = (url: string) => {
        window.open(url, '_blank');
    };
  
    const openProject = (url: string | null) => {
        if (url) {
            window.open(url, '_blank');
        }
    };
  
    onMount(() => {
        // Fetch data and populate the 'projects' array
        fetch('https://api.github.com/users/LinuxMistery00/repos')
            .then(response => response.json())
            .then((data: Project[]) => {
                projects = data.map((project: Project) => {
                    let faviconUrl: string | null = project.homepage ? `${project.homepage}/favicon.ico` : null;
                    let technologies: string[] = [];
  
                    switch (project.name) {
                        case 'Finance':
                            technologies = ['HTML5', 'CSS3', 'JavaScript', 'TypeScript', 'React', 'NodeJS', 'MongoDB'];
                            break;
                        case 'Calc':
                            technologies = ['HTML5', 'SASS', 'TypeScript', 'Angular'];
                            break;
                    }
  
                    return {
                        ...project,
                        faviconUrl,
                        technologies,
                    };
                });
            });
    });
</script>
  
<main>
    <h1 class="Title">{Title}</h1>
    <div class="Projects">
        {#each projects as project (project.id)}
        {#if !hiddenProjects.includes(project.name)}
            <Saos animation={"from-up 1.5s cubic-bezier(0.35, 0.5, 0.65, 0.95) both"}>
                <Projectcard name={project.name} repo_url={project.html_url} project_url={project.homepage}>
                    <img src={project.faviconUrl} alt="">
                    <div class="Buttons">
                        <button on:click={() => openRepository(project.html_url)}>Open Repo</button>
                        <button on:click={() => openProject(project.homepage)}>Open Project</button>
                    </div>
                </Projectcard>
            </Saos>
        {/if}
    {/each}
    
    </div>
</main>
  
<style>
    @keyframes -global-from-up {
  0% {
    transform: translateY(200vw);
    opacity: 0;
  }
  100% {
    transform: translateX(0);
    opacity: 1;
  }
}
    .Title {
        margin-top: 80vh;
        text-align: center;
        font-size: 6vh;
        color: #8844ee;
    }

    img {
        width: 50vh;
        border-radius: 3vh;
    }
  
    .Projects {
        display: flex;
        justify-content: center;
        flex-wrap: wrap;
        gap: 2vh;
    }

    .Buttons button {
        width: 30vh;
        height: 5vh;
        font-size: 3vh;
        border: 0;
        border-radius: 3vh;
        color: #f1f2f3;
        background-color: #8844ee;
    }

    .Buttons {
        display: flex;
    }
</style>

// Portfolio/src/app/home/components/home/projects/projects.component.ts
import { Component, OnInit, HostListener } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-projects',
  templateUrl: './projects.component.html',
  styleUrls: ['./projects.component.scss']
})
export class ProjectsComponent implements OnInit {
  Title: string = '<Projects/>';

  projects: any[] = [];
  hiddenProjects: string[] = [];

  constructor(private http: HttpClient) { }

  ngOnInit(): void {
    this.http.get<any[]>('https://api.github.com/users/LinuxMistery00/repos')
      .subscribe((data: any[]) => {
        this.projects = data.map((project: any) => ({
          ...project,
          isVisible: true,
          faviconUrl: `${project.homepage}/favicon.ico`,
          technologies: []
        }));

        const Finance = this.projects.find(project => project.name === 'Finance');
        if (Finance) {
          Finance.technologies = ['HTML5', 'CSS3', 'JavaScript', 'TypeScript', 'React', 'NodeJS', 'MongoDB'];
        }

        const Calc = this.projects.find(project => project.name === 'Calc');
        if (Calc) {
          Calc.technologies = ['HTML5', 'SASS', 'TypeScript', 'Angular'];
        }

        const Avaliacao = this.projects.find(project => project.name === 'Avaliacao');
        if (Avaliacao) {
          Avaliacao.technologies = ['HTML5', 'CSS3', 'JavaScript', 'TypeScript', 'Svelte'];
        }

        const PasswordGenerator = this.projects.find(project => project.name === 'PasswordGenerator');
        if (PasswordGenerator) {
          PasswordGenerator.technologies = ['HTML5', 'CSS3', 'JavaScript', 'TypeScript', 'React'];
        }

        const DevRegistration = this.projects.find(project => project.name === 'DevRegistration');
        if (DevRegistration) {
          DevRegistration.technologies = ['HTML5', 'CSS3', 'JavaScript', 'Nodejs', 'MongoDB'];
        }

        const Pokemons = this.projects.find(project => project.name === 'Pokemons');
        if (Pokemons) {
          Pokemons.technologies = ['HTML5', 'CSS3', 'TypeScript', 'React'];
        }

        const TextEditorVue = this.projects.find(project => project.name === 'TextEditorVue');
        if (TextEditorVue) {
          TextEditorVue.technologies = ['HTML5', 'Vue', 'JavaScript', 'TypeScript'];
        }

        const Posfirst = this.projects.find(project => project.name === 'Posfirst');
        if (TextEditorVue) {
          Posfirst.technologies = ['HTML5', 'CSS3', 'TypeScript', 'React', 'PostgreSQL'];
        }

        const Firefox = this.projects.find(project => project.name === 'Firefox');
        if (Firefox) {
          Firefox.technologies = ['HTML5', 'SASS', 'TypeScript', 'Angular'];
        }
      });

    this.hiddenProjects.push('Naval-Battle');
    this.hiddenProjects.push('LinuxMistery00');
    this.hiddenProjects.push('ProgramadorOrientadoaObjetoMain');
    this.hiddenProjects.push('Indalo');
    this.hiddenProjects.push('Windows95');
    this.hiddenProjects.push('Portfolio');
    this.hiddenProjects.push('To-Do-List');
    this.hiddenProjects.push('E-Commerce');
    this.hiddenProjects.push('Tic-Tac-Toe');
    this.hiddenProjects.push('Curso-de-Java-RocketSeat');
    this.hiddenProjects.push('TextsForYou');
    this.hiddenProjects.push('Houses');
    this.hiddenProjects.push('DevRegistration');
    this.hiddenProjects.push('Posfirst');
    this.hiddenProjects.push('Pokemons');
    this.hiddenProjects.push('Avaliacao');
    this.hiddenProjects.push('Yulang');
    this.hiddenProjects.push('linguist');
    this.hiddenProjects.push('exercicios');
  }

  openRepository(url: string) {
    window.open(url, '_blank');
  }

  openWebsite(url: string) {
    if (url) {
      window.open(url, '_blank');
    }
  }

  toggleVisibility(project: any) {
    project.isVisible = !project.isVisible;
  }

  isProjectHidden(project: any): boolean {
    return this.hiddenProjects.includes(project.name);
  }
}
<div class="Projects">
  <div *ngFor="let project of projects">
    <app-projectcard *ngIf="!isProjectHidden(project)">
      <div class="front-content">
      <h2 class="ProjectName">{{ project.name }}</h2>
      <img src="{{ project.faviconUrl }}" alt="">
      </div>
      <div class="back-content">
      <div class="Techs">
        <h1 *ngFor="let tech of project.technologies" class="Tech">{{ tech }}</h1>
        </div>
        <h2 class="ProjectDescription">{{ project.description }}</h2>
        <div class="Buttons">
          <button (click)="openRepository(project.html_url)">Repository</button>
          <button (click)="openWebsite(project.homepage)">Website</button>
        </div>
      </div>
    </app-projectcard>
  </div>
</div>
